//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NB_AMQP {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Mysetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static Mysetting defaultInstance = ((Mysetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Mysetting())));
        
        public static Mysetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int temperature_threshold {
            get {
                return ((int)(this["temperature_threshold"]));
            }
            set {
                this["temperature_threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int humidity_threshold {
            get {
                return ((int)(this["humidity_threshold"]));
            }
            set {
                this["humidity_threshold"] = value;
            }
        }
    }
}
